cabal-version: 2.4
name: blog
version: 0.1.0.0
author: Ori Livson
maintainer: ori.livson.blog@gmail.com

flag dev
  description: Enable development mode
  default: False

flag no-comments
  description: Enable development mode
  default: False

executable blog
  main-is: Main.hs
  build-depends:
    aeson,
    base ^>=4.18.3.0,
    binary,
    commonmark,
    commonmark-extensions,
    containers,
    dir-traverse,
    directory,
    filepath,
    http-conduit,
    lucid,
    lucid-svg,
    network-uri,
    optparse-applicative,
    pandoc,
    tagsoup,
    text,
    time,
    rss

  default-extensions:
    DataKinds
    DeriveGeneric
    FlexibleInstances
    GADTs
    InstanceSigs
    MultiParamTypeClasses
    NamedFieldPuns
    OverloadedLists
    OverloadedStrings
    RankNTypes
    RecordWildCards
    TypeOperators

  other-modules:
    Assertions
    RssGenerator
    Config
    GitHub
    LucidUtils
    PageSpecs
    Templates

  ghc-options:
    -Wall

  hs-source-dirs: app
  default-language: Haskell2010

  if flag(dev)
    cpp-options: -DDEV_MODE
  else
    cpp-options: -DPROD_MODE

  if flag(no-comments)
    cpp-options: -DNO_COMMENTS
  else
    cpp-options: -DCOMMENTS

executable tools
  main-is: Main.hs

  build-depends:
    base ^>=4.18.3.0,
    aeson,
    binary,
    commonmark,
    commonmark-extensions,
    containers,
    dir-traverse,
    directory,
    filepath,
    http-conduit,
    lucid,
    lucid-svg,
    network-uri,
    optparse-applicative,
    pandoc,
    tagsoup,
    text,
    time,
    rss

  hs-source-dirs: tools app
  default-language: Haskell2010

  ghc-options:
    -Wall